[workspace]
members = ["crates/*"]
resolver = "2"

[profile.release]
#codegen-units = 1 # 0.1Mb improvement. slower compilation.
#lto = "fat" # 0.1Mb improvement. slower compilation.
#opt-level = "z" # 0.5 Mb improvement. slower compilation and performance.
